version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    env_file:
      - .env.local
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env.local
    ports:
      - '5432:5432'
    volumes:
      - database_pg:/var/lib/postgresql/data

volumes:
  database_pg:

networks:
  app-network:
