version: '3'

services:
  database:
    image: 'postgres:14.2-alpine'
    restart: always
    networks:
      - app-network
    ports:
      - '5432:5432'
    env_file:
      - ./.env

  app:
    container_name: 'backend_app'
    environment:
      - NODE_ENV=prod
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_PORT=${SERVER_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_DB_TEST=${POSTGRES_DB_TEST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - app-network
    volumes:
      - type: bind
        source: ./src/modules/database/
        target: /app/src/modules/database/
    restart: always
    command: npm run start:prod

networks:
  app-network:
